name = "qk_core_service"
main = "src/index.ts"

compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-11-11"

[dev]
port = 8788

[[routes]]
pattern = "api.questkeeper.app/v1/core*"
zone_name = "questkeeper.app"

[[services]]
binding = "TASK_COMPLETE_SERVICE"
service = "qk_social_service"

[vars]
SUPABASE_URL = "https://mzudaknbrzixjkvjqayw.supabase.co"

[placement]
mode = "off"

[env.dev.vars]
ENVIRONMENT = "dev"
SUPABASE_URL = "https://mzudaknbrzixjkvjqayw.supabase.co"